AWSTemplateFormatVersion: '2010-09-09'
Description: Template de exemplo de VPC
Resources:
  MinhaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true