AWSTemplateFormatVersion: '2010-09-09'
Description: Template de exemplo de instância EC2
Resources:
  MinhaInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0